### ISSUE TITLE
doesn't see chromebook

### ISSUE THREAD

**Issue by bluenevus** [onedoes/snapdrop#83]
I went to your website between 2 devices.  1 Windows, the 2nd chromebook.  Neither could see each other.    I installed it locally, served it up in dev mode and the same occurs on my local test instance

**Comment by douglasduteil** [comment]
Our fork has some issues.
I would recommend that you come back to the original code https://github.com/RobinLinus/snapdrop now that it woks again :)
 https://snapdrop.net
